import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import type { CampaignProject } from "../../src/authoring/types";

test("U-AUTHOR edits height, registers and places a new object, preserves invalid-import drafts and exports for Codex", async ({ page }, info) => {
  await page.goto("/campaign-editor.html");
  await expect(page.getByRole("heading", { name: "캠페인 제작", exact: true })).toBeVisible();
  const status = page.getByRole("status");
  await page.getByLabel("높이", { exact: true }).fill("4");
  await page.getByRole("button", { name: "높이 적용", exact: true }).click();
  await expect(status).toContainText("높이를 저장");
  await page.getByRole("button", { name: "실행 취소", exact: true }).click();
  await expect(page.getByLabel("높이", { exact: true })).toHaveValue("3");
  await page.getByRole("button", { name: "다시 실행", exact: true }).click();
  await expect(page.getByLabel("높이", { exact: true })).toHaveValue("4");
  await page.getByRole("button", { name: "오브젝트", exact: true }).click();
  await page.getByLabel("오브젝트 ID", { exact: true }).fill("authoring-crate");
  await page.getByLabel("이름", { exact: true }).fill("보급 상자");
  await page.getByRole("button", { name: "오브젝트 정의 추가", exact: true }).click();
  await expect(status).toContainText("새 오브젝트");
  await page.getByRole("button", { name: "맵", exact: true }).click();
  await page.getByLabel("오브젝트", { exact: true }).selectOption("authoring-crate");
  await page.getByRole("button", { name: "오브젝트 배치", exact: true }).click();
  await expect(status).toContainText("배치했습니다");
  await expect(page.getByRole("gridcell", { name: "타일 0,0", exact: true })).toContainText("◆");
  await page.getByLabel("JSON 불러오기", { exact: true }).setInputFiles({ name: "bad.json", mimeType: "application/json", buffer: Buffer.from('{"version":2}') });
  await expect(status).toHaveClass(/error/);
  await expect(page.getByRole("gridcell", { name: "타일 0,0", exact: true })).toContainText("◆");
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "JSON 내보내기", exact: true }).click();
  const artifact = await download;
  const project = JSON.parse(await readFile((await artifact.path())!, "utf8")) as CampaignProject;
  expect(project.presentation.elevations.maps["encounter.willow-rescue"]![0]).toBe(4);
  expect(project.presentation.objects.find(o => o.id === "authoring-crate")?.visual).toBe("object.chest");
  expect(project.content.scenarios.find(s => s.id === "encounter.willow-rescue")!.map.objects.some(o => o.traits.some(t => t.id === "authoring-crate"))).toBe(true);
  page.on("dialog", dialog => dialog.accept());
  await page.reload();
  await page.getByRole("button", { name: "저장한 초안 복원", exact: true }).click();
  await expect(page.getByRole("gridcell", { name: "타일 0,0", exact: true })).toContainText("◆");
  await page.screenshot({ path: info.outputPath("campaign-map.png") });
});

test("U-AUTHOR edits dialogue and rewards, previews the saved line and duplicates an encounter into campaign order", async ({ page }, info) => {
  await page.goto("/campaign-editor.html");
  await page.getByRole("button", { name: "다이얼로그", exact: true }).click();
  await page.getByLabel("대사 본문", { exact: true }).fill("주민들을 위해 새 길을 열어주세요.");
  await page.getByRole("button", { name: "대사 저장", exact: true }).click();
  await page.getByRole("button", { name: "재생 미리보기", exact: true }).click();
  const dialogue = page.getByRole("dialog", { name: "대사 미리보기", exact: true });
  await expect(dialogue).toContainText("주민들을 위해 새 길을 열어주세요.");
  await page.keyboard.press("Escape");
  await expect(dialogue).toHaveCount(0);
  await page.getByRole("button", { name: "보상", exact: true }).click();
  await page.getByLabel("경험치", { exact: true }).fill("125");
  await page.getByLabel("종류", { exact: true }).selectOption("card");
  await page.getByLabel("정의", { exact: true }).selectOption("card.shield-spell");
  await page.getByRole("button", { name: "선택 항목 추가", exact: true }).click();
  await page.getByRole("button", { name: "보상·경험치 저장", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("캠페인 초안");
  await page.screenshot({ path: info.outputPath("campaign-reward.png") });
  await page.getByText("인카운터 복제", { exact: true }).click();
  await page.getByLabel("새 인카운터 ID", { exact: true }).fill("encounter.authoring-copy");
  await page.getByLabel("새 인카운터 이름", { exact: true }).fill("새 숲길");
  await page.getByRole("button", { name: "현재 전장 복제·연결", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("복제하고");
  await page.getByRole("button", { name: "검증", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("검증 통과");
  await page.getByText("전체 프로젝트 JSON", { exact: true }).click();
  const project = JSON.parse(await page.locator("#project-json").inputValue()) as CampaignProject;
  const campaign = project.content.adventures.find(a => a.id === "adventure.willowbrook")!;
  expect(campaign.encounterIds.at(-1)).toBe("encounter.authoring-copy");
  expect(campaign.experienceAwards.find(a => a.afterEncounterId === "encounter.willow-rescue")?.amount).toBe(125);
  expect(campaign.rewards.find(r => r.afterEncounterId === "encounter.willow-rescue")!.choices).toContainEqual({ kind: "card", definitionId: "card.shield-spell" });
  expect(project.dialogue.scenes["encounter.authoring-copy.briefing"]!.lines[0]!.text).toContain("새 길");
});

test("U-AUTHOR structured encounter forms reject a blocked placement, retain the draft and edit targets and party spawns", async ({ page }) => {
  await page.goto("/campaign-editor.html");
  await page.getByRole("button", { name: "인카운터", exact: true }).click();
  await page.getByLabel("적 인스턴스 ID", { exact: true }).fill("editor-enemy");
  await page.getByLabel("적 정의", { exact: true }).selectOption("enemy.dark-elf-warrior");
  await page.getByLabel("적 X", { exact: true }).fill("1");
  await page.getByLabel("적 Y", { exact: true }).fill("2");
  await page.getByRole("button", { name: "적 배치 저장", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("ACTOR_TILE_BLOCKED");
  await expect(page.getByLabel("적 인스턴스 ID", { exact: true })).toHaveValue("editor-enemy");
  await page.getByLabel("적 X", { exact: true }).fill("0");
  await page.getByRole("button", { name: "적 배치 저장", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("인카운터 초안");
  await page.getByLabel("승리 방식", { exact: true }).selectOption("resolve-objectives");
  await page.getByText("필수 목표 선택", { exact: true }).click();
  await page.getByLabel("editor-enemy", { exact: true }).check();
  await page.getByRole("button", { name: "이름·목표 저장", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("인카운터 초안");
  await page.getByLabel("1번 Y", { exact: true }).fill("18");
  await page.getByRole("button", { name: "시작 위치 저장", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("인카운터 초안");
  await page.getByText("전체 프로젝트 JSON", { exact: true }).click();
  const project = JSON.parse(await page.locator("#project-json").inputValue()) as CampaignProject;
  const encounter = project.content.scenarios.find(s => s.id === "encounter.willow-rescue")!;
  expect(encounter.rules?.victory?.enemyIds).toEqual(["editor-enemy"]);
  expect(encounter.placements.find(p => p.instanceId === "editor-enemy")?.position).toEqual({ x: 0, y: 2 });
  expect(encounter.partySpawnSlots[0]!.position).toEqual({ x: 9, y: 18 });
});
